name: Build and upload

on: workflow_dispatch

env:
  MSVC: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.34.31933
  WINSDK: C:/Program Files (x86)/Windows Kits/10
  WINSDK_VERSION: 10.0.22621.0

jobs:
  build:
    name: ${{ matrix.platform.name }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'Linux (x64)'   ,os: ubuntu-22.04              }
          - { name: 'Windows (x64)' ,os: windows-2022              }
          - { name: 'Mac (x64)'     ,os: macos-12                  }
          - { name: 'Mac (arm64)'   ,os: macos-12     ,arch: arm64 }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v3

      - if: ${{ startsWith(matrix.platform.os, 'ubuntu-') }}
        run: scripts/install-deps-ubuntu.sh

      - if: ${{ startsWith(matrix.platform.os, 'macos-') }}
        run: scripts/install-deps-mac.sh

      - if: ${{ startsWith(matrix.platform.os, 'windows-') }}
        shell: bash
        run: |
          scripts/install-deps-windows.cmd
          echo '${{ env.MSVC }}/bin/Hostx64/x64' >> $GITHUB_PATH
          echo '${{ env.WINSDK }}/bin/${{ env.WINSDK_VERSION }}/x64' >> $GITHUB_PATH
          LIB="${{ env.WINSDK }}/Lib/${{ env.WINSDK_VERSION }}/um/x64"
          LIB="${{ env.WINSDK }}/Lib/${{ env.WINSDK_VERSION }}/ucrt/x64;$LIB"
          LIB="${{ env.MSVC }}/lib/x64;$LIB"
          echo "LIB=$LIB" >> $GITHUB_ENV
          INCLUDE="${{ env.MSVC }}/include"
          INCLUDE="${{ env.WINSDK }}/Include/${{ env.WINSDK_VERSION }}/ucrt;$INCLUDE"
          INCLUDE="${{ env.WINSDK }}/Include/${{ env.WINSDK_VERSION }}/um;$INCLUDE"
          INCLUDE="${{ env.WINSDK }}/Include/${{ env.WINSDK_VERSION }}/shared;$INCLUDE"
          INCLUDE="${{ env.WINSDK }}/Include/${{ env.WINSDK_VERSION }}/winrt;$INCLUDE"
          echo "INCLUDE=$INCLUDE" >> $GITHUB_ENV

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROSS_COMPILE_ARCH: ${{ matrix.platform.arch }}
        run: npm run release
