name: Build and upload

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.platform.name }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'Linux (x64)'     ,os: ubuntu-22.04              }
          - { name: 'Linux (arm64)'   ,os: ubuntu-22.04-arm          }
          # - { name: 'Windows (x64)'   ,os: windows-2025              }
          # - { name: 'Windows (arm64)' ,os: windows-11-arm            }
          # - { name: 'Mac (x64)'       ,os: macos-15     ,arch: x64   }
          # - { name: 'Mac (arm64)'     ,os: macos-15     ,arch: arm64 }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v4

      - if: ${{ startsWith(matrix.platform.os, 'ubuntu-') && endsWith(matrix.platform.os, '-arm') }}
        run: |
          curl -fsSL https://go.dev/dl/go1.25.0.linux-arm64.tar.gz > go.tar.gz
          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go.tar.gz
          echo "PATH=/usr/local/go/bin:$PATH" >> $GITHUB_ENV

      - if: ${{ startsWith(matrix.platform.os, 'ubuntu-') }}
        run: sudo apt-get update && sudo ./scripts/install-deps-ubuntu.sh

      - if: ${{ startsWith(matrix.platform.os, 'windows-') }}
        shell: bash
        run: |
          MSVC_DIR='C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC'
          MSVC_VERSION=$(ls "${MSVC_DIR}" | sort -Vr | head -n1)
          MSVC="${MSVC_DIR}/${MSVC_VERSION}"
          WINSDK_DIR='C:/Program Files (x86)/Windows Kits/10'
          WINSDK_VERSION=$(ls "${WINSDK_DIR}/bin" | grep -E '^[0-9]' | sort -Vr | head -n1)
          echo "${MSVC}/bin/Hostx64/x64" >> $GITHUB_PATH
          echo "${WINSDK_DIR}/bin/${WINSDK_VERSION}/x64" >> $GITHUB_PATH
          LIB="${WINSDK_DIR}/Lib/${WINSDK_VERSION}/um/x64"
          LIB="${WINSDK_DIR}/Lib/${WINSDK_VERSION}/ucrt/x64;$LIB"
          LIB="${MSVC}/lib/x64;$LIB"
          echo "LIB=$LIB" >> $GITHUB_ENV
          INCLUDE="${MSVC}/include"
          INCLUDE="${WINSDK_DIR}/Include/${WINSDK_VERSION}/ucrt;$INCLUDE"
          INCLUDE="${WINSDK_DIR}/Include/${WINSDK_VERSION}/um;$INCLUDE"
          INCLUDE="${WINSDK_DIR}/Include/${WINSDK_VERSION}/shared;$INCLUDE"
          INCLUDE="${WINSDK_DIR}/Include/${WINSDK_VERSION}/winrt;$INCLUDE"
          echo "INCLUDE=$INCLUDE" >> $GITHUB_ENV
          scripts/install-deps-windows.cmd

      - if: ${{ startsWith(matrix.platform.os, 'macos-') }}
        run: brew update && ./scripts/install-deps-mac.sh

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROSS_COMPILE_ARCH: ${{ matrix.platform.arch }}
        run: npm run release
